### PR TITLE
Add Queue UI

### LINKED ISSUE #32: [Feature] Queue UI
# Description
Adds a frontend for the user to queue a session.

# Sub-Tasks
- #33 
- #34 
- #35

### LINKED ISSUE #33: [Queue UI] Add Queue UI
# Description
Add a form for the user to select difficulty and enter the queue.

# Parent Task
- #32

### LINKED ISSUE #34: [Queue UI] Add Countdown Timer
# Description
Add a countdown timer when the user enters the queue. 
Allow the user the leave the queue during the countdown period

# Parent Task
- #32

### LINKED ISSUE #35: [Queue UI] Add Session Page
# Description
Add a placeholder page when the user is successfully matched

# Parent Task
- #32 

# Related Task

### PR DESCRIPTION
**Pull request by KwanHW**
# Changes
This PR
- enhances the landing page
- adds a difficulty selection interface
- adds a countdown timer interface
- adds a placeholder session interface

**Note:** This feature is not integrated with the backend yet (see `Prerequisites`).

# Prerequisites
- #38 

# Related Features
- Closes #32

# Related Issues 
- Closes #33 
- Closes #34 
- Closes #35

## Images
**Landing Page and Difficulty Selection**
Landing page

**Countdown Timer**
Countdown Timer

**Placeholder session room**
Session Room

### CODE REVIEW

**Comment by laughingkid-sg** [comment]
### Possible bugs 

1. All difficulty options are selected when leaving the queue
2. Some options will auto-select when clicking on the join queue button (see 0:09 in the video)
  - In this video, `Hard` was already de-selected, however clicking on `Find Buddy` auto select `Hard`

https://user-images.githubusercontent.com/24849568/189394195-87de1840-955e-4409-ae28-b0b45da59948.mov

**Comment by laughingkid-sg** [comment]
## Possible bugs

- Buttons should not show clickable on hover
- If buttons are able to be used to select difficulty then it is not working

Screenshot 2022-09-10 at 5 57 23 PM

**Comment by ooawagaeri** [comment]
# Possible Bug
- Button is clickable beyond the button shape

https://user-images.githubusercontent.com/33891863/189510051-8af4e1ce-f392-4fc4-8e44-a6b4510e39f8.mp4

**Review by sharpstorm — APPROVED** [review]
LGTM.

**Pull request merged**
